#!/usr/bin/env python
"""Turn the audit_partition.py JSON reports into one markdown table."""

import argparse
import glob
import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

DATASET_ORDER = ["cora", "citeseer", "pubmed", "cs", "reddit"]
METHOD_ORDER = ["ccp", "gae", "oslom", "slpa", "infomap"]


def sort_key(report):
    dataset = report.get("dataset", "")
    method = report.get("method", "")
    config = report.get("ccp_config") or {}
    return (
        DATASET_ORDER.index(dataset) if dataset in DATASET_ORDER else 99,
        METHOD_ORDER.index(method) if method in METHOD_ORDER else 99,
        str((report.get("gae_report") or {}).get("device", "")),
        int(config.get("ccp_tail_min_size", 0) or 0),
        report.get("seed", 0),
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reports", default=os.path.join(
        REPO_ROOT, "reproduction", "results", "partition", "*.json"))
    parser.add_argument("--out", default=os.path.join(
        REPO_ROOT, "reproduction", "results", "partition_audit.md"))
    options = parser.parse_args()

    reports = []
    for path in sorted(glob.glob(options.reports)):
        with open(path) as handle:
            reports.append(json.load(handle))
    if not reports:
        raise SystemExit("no partition reports under {}".format(options.reports))
    reports.sort(key=sort_key)

    threads = sorted({report.get("num_threads") for report in reports} - {None})
    lines = [
        "<!-- generated by reproduction/scripts/make_partition_table.py -->",
        "# Community-detection audit",
        "",
        "Partition stage measured in isolation (no training, no mapped-graph "
        "construction unless the `mapped-edge (s)` column is filled), "
        "`--num-threads {}`.  `hold-out` is `--ccp-protect-eval-nodes`, `tail` is "
        "`--ccp-tail-min-size`, `device` is where the detector ran.".format(
            ", ".join(str(value) for value in threads) or "n/a"),
        "",
        "| Dataset | Method | Device | Hold-out | Tail | Seed | Communities | Compression "
        "| Coverage | Overlapping nodes | Memberships/node (mean, max) | Singletons "
        "| Size median | Size max | Label purity | Modularity (primary) | Detector (s) "
        "| Mapped-edge (s) | Community hash |",
        "|---" * 19 + "|",
    ]
    for report in reports:
        config = report.get("ccp_config") or {}
        gae = report.get("gae_report") or {}
        lines.append(
            "| {} | {} | {} | {} | {} | {} | {} | {:.4f} | {:.4f} | {:.4f} | {:.3f}, {} | {} "
            "| {:.1f} | {} | {:.4f} | {:.4f} | {:.2f} | {} | {} |".format(
                report.get("dataset"),
                report.get("method"),
                gae.get("device", "cpu"),
                config.get("ccp_protect_eval_nodes", "n/a"),
                config.get("ccp_tail_min_size", 0),
                report.get("seed"),
                report["num_communities"],
                report["compression_ratio"],
                report["coverage"],
                report["overlapping_node_fraction"],
                report["memberships_per_node_mean"],
                report["memberships_per_node_max"],
                report["singleton_communities"],
                report["community_size_median"],
                report["community_size_max"],
                report.get("label_purity_mean", float("nan")),
                report.get("modularity_primary", float("nan")),
                report.get("elapsed_seconds", float("nan")),
                ("%.2f" % report["edge_mapping_seconds"])
                if report.get("edge_mapping_seconds") is not None else "-",
                report.get("community_hash", "-"),
            )
        )

    text = "\n".join(lines) + "\n"
    with open(options.out, "w") as handle:
        handle.write(text)
    print(text)
    print("wrote {}".format(os.path.relpath(options.out, REPO_ROOT)))


if __name__ == "__main__":
    main()
